name: Generate GitHub contribution snake

on:
  schedule:
    - cron: "0 */24 * * *" # Every 24 hours
  workflow_dispatch:
 
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate GitHub contribution snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg?color_snake=#0969DA
            github-contribution-grid-snake-dark.svg?color_snake=#0969DA&palette=github-dark

      - name: Commit updated SVGs to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub contribution snake SVGs"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
